:PROPERTIES:
:CATEGORY: macros
:END:

* TODO Don't duplicate food/fluid/etc items in data files

This also means making sure that ids for items are always unique.

* TODO Remove food/fluid/workout items that have already been logged

There needs to be a way to remove food/fluid/workout items from the log.

* TODO Update workouts instead of adding new records

Workouts are a bit different. If I workout, I should be able to add sets later
on (especially with GtG-style workouts).

* TODO Modify workouts so that they're actually workouts

Currently, workout logging favors a grease-the-groove approach but I do full
workouts, too, that should be accounted for appropriately. Figure out how to
track both appropriately.

* TODO Remove items (foods, fluids, workouts, etc)

* TODO Explore using metadata instead of different variables

Now that we're tracking multiple things, there are several flags that we use to
determine whether or not to save data (e.g. no need to save if something hasn't
changed).

Perhaps we could use metadata on the atom that holds the actual data instead of
separate variables to handle this?

I've never really used it so I don't know how metadata works, right now. Figure
it out and see if it makes sense as a solution.

* TODO Allow working on logs from different days

I want to be able to modify a log from (e.g.) yesterday and add final calories,
fluids, etc. This means I should be able to change a log for a different day.
Currently, the app will overwrite today's log with any changes because
~with-log~ will set the log file to the current date.

There needs to be a way to specify the log file before making changes, etc.
